version: '3'
services:
  auth:
    image: cyberadvance/authen-service
    ports:
      - "3001:3000"
    environment:
      - MONGO_DB_URI=mongodb://54.255.235.162/rabu-test-db
      - AMQP_URL=amqp://18.136.211.19
      # - AMQP_URL=amqp://xeyvpanu:ZUkVpxBMXr1Dm2cQOQZyKumESIPohGyJ@vulture.rmq.cloudamqp.com/xeyvpanu
    deploy:
      replicas: 1

  teams:
    image: cyberadvance/team-service
    ports:
      - "3002:3000"
    depends_on:
      - auth
    environment:
      - MONGO_DB_URI=mongodb://54.255.235.162/rabu-test-db
      - AMQP_URL=amqp://18.136.211.19
    deploy:
      replicas: 1

  products:
    image: cyberadvance/product-service
    ports:
      - "3003:3000"
    depends_on:
      - auth
    environment:
      - MONGO_DB_URI=mongodb://54.255.235.162/rabu-test-db
      - AMQP_URL=amqp://18.136.211.19
    deploy:
      replicas: 1

  orders:
    image: cyberadvance/order-service
    ports:
      - "3004:3000"
    depends_on:
      - auth
    environment:
      - MONGO_DB_URI=mongodb://54.255.235.162/rabu-test-db
      - AMQP_URL=amqp://18.136.211.19
    deploy:
      replicas: 1

  customers:
    image: cyberadvance/customer-service
    ports:
      - "3005:3000"
    depends_on:
      - auth
    environment:
      - MONGO_DB_URI=mongodb://54.255.235.162/rabu-test-db
      - AMQP_URL=amqp://18.136.211.19
    deploy:
      replicas: 1

  monitors:
    image: cyberadvance/monitor-service
    ports:
      - "3006:3000"
    depends_on:
      - auth
    environment:
      - MONGO_DB_URI=mongodb://54.255.235.162/rabu-test-db
      - AMQP_URL=amqp://18.136.211.19
    deploy:
      replicas: 1