version: '3'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    deploy:
      replicas: 1

  auth:
    image: authen-service
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/auth
    deploy:
      replicas: 1

  team:
    image: team-service
    ports:
      - "3002:3000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/team
    deploy:
      replicas: 1

  product:
    image: product-service
    ports:
      - "3003:3000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/product
    deploy:
      replicas: 1

  order:
    image: order-service
    ports:
      - "3004:3000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/order
    deploy:
      replicas: 1